name: Update manifests

on:
  workflow_dispatch:
  schedule:
    - cron: "20 */6 * * *"

permissions:
  contents: write

jobs:
  update:
    runs-on: windows-latest
    steps:
      - name: Check out bucket
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Check for new releases
        uses: ScoopInstaller/GithubActions@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SKIP_UPDATED: 1
